### ISSUE TITLE
exception should not be thrown when checking blob.exists() on a non-existing blob

### ISSUE THREAD

**Issue by azuruce** [fullstorydev/emulators#131]
reproduce:
run gcsemulator emulator and point to localhost:4443

then run
STORAGE_EMULATOR_HOST='http://localhost:4443' python

from google.cloud import storage
client = storage.Client()
blob = storage.Blob.from_string('gs://mybucket/non-existing-file', client=client)
blob.exists()

error is
        error_message = payload.get("error", {}).get("message", "unknown error")
        errors = payload.get("error", {}).get("errors", ())
        # In JSON, details are already formatted in developer-friendly way.
        details = payload.get("error", {}).get("details", ())
        error_info = list(
            filter(
>               lambda detail: detail.get("@type", "")
                == "type.googleapis.com/google.rpc.ErrorInfo",
                details,
            )
        )
E       TypeError: 'NoneType' object is not iterable

The reason is gcsemulator returns error message in this sample format, but details=None, it should not pass details

{'code': 404, 'message': 'XYZSUCCESS not found', 'details': None, 'Body': '', 'Header': None, 'Errors': None}

**Comment by dragonsinth** [comment]
Hi @azuruce thanks for the report.  Can you paste the JSON the emulator currently returns, and the JSON you would have expected it to return?

**Comment by azuruce** [comment]
hi, the response from gcsemulator is

{'code': 404, 'message': 'bucket/path/job_id/_SUCCESS not found', 'details': None, 'Body': '', 'Header': None, 'Errors': None}

the response from gcloud is

{'code': 404, 'message': 'No such object: bucket/path/job_id/_SUCCESS', 'errors': [{'message': 'No such object: bucket/path/job_id/_SUCCESS', 'domain': 'global', 'reason': 'notFound'}]}}

You just need to remve the details key for gcsemulator to work
{'code': 404, 'message': 'bucket/path/job_id/_SUCCESS not found', 'Body': '', 'Header': None, 'Errors': None}

fake-gcs-server returns a non-jsonable response, which is even worse.

**Comment by dragonsinth** [comment]
@azuruce that can't be the actual original JSON coming over the write, `None` is from Python, not JSON.

**Comment by dragonsinth** [comment]
```json
        {
          "error": {
            "code": 404,
            "message": "The specified bucket does not exist.",
            "errors": [
              {
                "message": "The specified bucket does not exist.",
                "domain": "global",
                "reason": "notFound"
              }
            ]
          }
        }
```
Here's an example I pulled from raw_http_test of real GCS response.

**Comment by dragonsinth** [comment]
```json
{
  "error": {
    "code": 404,
    "message": "http error 404: fullstory-non-existant-bucket/gscemu-test-deletion.txt not found",
    "details": null,
    "Body": "",
    "Header": null,
    "Errors": null
  }
}
```
What we're doing.

**Comment by azuruce** [comment]
hi, dragonsinth, the code the raise the exception is here. When details is set to null at line 493, the foreach will fail.

https://github.com/googleapis/python-api-core/blob/3c5e034fdd6f8a98d2fd9d4a927c58c202823767/google/api_core/exceptions.py#L498

Basically can you change output to
{
  "error": {
    "code": 404,
    "message": "http error 404: fullstory-non-existant-bucket/gscemu-test-deletion.txt not found",
    "Body": "",
    "Header": null,
    "Errors": null
  }
}
