### ISSUE TITLE
Emulator returns success for missing items when using batch endpoint

### ISSUE THREAD

**Issue by franklinlindemberg** [fullstorydev/emulators#20]
Probably similar to https://github.com/fullstorydev/emulators/issues/7

When calling batch endpoint in real GCS, files that doesn't exist return NotFound. When using the emulator it never returns an error.

Real GCS returns an *googleapi.Error with Code 404

**Comment by dragonsinth** [comment]
That's a lot of negativity could we rephrase in a positive way? 🤣

"Emulator returns success for missing items when using batch endpoint" or something

**Comment by franklinlindemberg** [comment]
hahaha agreed, I created with the issue mindset. Updated it
