### ISSUE TITLE
Resumable upload is broken using official go storage client

### ISSUE THREAD

**Issue by Edholm** [fullstorydev/emulators#4]
## Description
_this issue is for the GCS emulator_

When doing a resumable upload a post request is sent to the emulator which returns the "real" address to a file in GCS in the `Location` header.

Example POST to the emulator from the official go client:
`POST http://localhost:8080/upload/storage/v1/b/my-bucket/o`
The response contains has the `Location` header pointing to `https://www.googleapis.com/storage/v1/b/my-bucket/o/my-object.ext?upload_id=4`

This location field is then used by the official storage library for further requests, essentially skipping the emulator for all subsequent upload chucks (hanging until context is cancelled in my case).

### Fix 1
I've verified a fix by manually changing the location header value to `http://localhost:8080/storage/v1/b/my-bucket/o/my-object.ext?upload_id=4` before it is used by the official client. I did so by overriding the value using the debugger in this file: `google.golang.org/api@v0.54.0/storage/v1/storage-gen.go:10295`

I suspect these fields come from `storage/gcsemu/meta.go`?

### Fix 2
Setting the chunk size of the writer to >= file.size() also solves this issue, but then it isn't a resumable upload...

It would be nice if you could update so that the location header points to the local emulator rather than the real official GCS url.

_I know you say that I shouldn't rely on `STORAGE_EMULATOR_HOST`, but with this (hopefully) minor fix the library works as expected for me at least..._

#### EDIT:
I've verified that this quickfix solves the issue for me:
```diff
diff --git a/storage/gcsemu/meta.go b/storage/gcsemu/meta.go
index aee05f1..df8740e 100644
--- a/storage/gcsemu/meta.go
+++ b/storage/gcsemu/meta.go
@@ -47,10 +47,10 @@ func scrubMeta(meta *storage.Object) {
 // Return the URL for a file.  Note that this will generally not be useful as an input an http request due to the way
 // that net/url does character substitution (see comments above).
 func bucketUrl(bucket string) string {
-	return fmt.Sprintf("https://www.googleapis.com/storage/v1/b/%s", bucket)
+	return fmt.Sprintf("http://localhost:8080/storage/v1/b/%s", bucket)
 }
 
 // Return the URL for a file.
 func objectUrl(bucket string, filepath string) string {
-	return fmt.Sprintf("https://www.googleapis.com/storage/v1/b/%s/o/%s", bucket, filepath)
+	return fmt.Sprintf("http://localhost:8080/storage/v1/b/%s/o/%s", bucket, filepath)
 }
 ```

**Comment by dragonsinth** [comment]
Hi @Edholm -- we haven't tried to support `STORAGE_EMULATOR_HOST` due to these two issues:

- https://github.com/googleapis/google-cloud-go/issues/2476
- https://github.com/googleapis/google-cloud-go/issues/4444

That's why we provided the `gcsemu.NewClient` helper, which completely swaps out the http transport layer and should work with resumable upload.  Once those fixes are released (they might already be?), we can look at making sure that `STORAGE_EMULATOR_HOST` on the newest version of the client lib works.

That being said, the emulator could probably be smarter at looking at the incoming request host and constructing outbound URLs that make sense in light of the incoming host header.

**Comment by Edholm** [comment]
> Hi @Edholm -- we haven't tried to support `STORAGE_EMULATOR_HOST` due to these two issues:
> 
> * [storage: when using an emulator, it is not possible to use the same Client object for both uploading and other operations googleapis/google-cloud-go#2476](https://github.com/googleapis/google-cloud-go/issues/2476)
> * [Storage: empty readHost when STORAGE_EMULATOR_HOST is set to host:port googleapis/google-cloud-go#4444](https://github.com/googleapis/google-cloud-go/issues/4444)
> 
> That's why we provided the `gcsemu.NewClient` helper, which completely swaps out the http transport layer and should work with resumable upload. Once those fixes are released (they might already be?), we can look at making sure that `STORAGE_EMULATOR_HOST` on the newest version of the client lib works.
> 
> That being said, the emulator could probably be smarter at looking at the incoming request host and constructing outbound URLs that make sense in light of the incoming host header.

I saw those issues and I think they seem to be fixed quite recently actually. The reason I went with the environment variable approach and not using your custom client is that I currently aren't using your lib in my app, I'm only using the standalone CLI. 

But the good thing is that the issue has been identified and the fix is seemingly easy. Thanks for responding!

**Comment by dragonsinth** [comment]
@Edholm can you give https://github.com/fullstorydev/emulators/pull/5 a whirl and see if this does it for you?

**Comment by Edholm** [comment]
> @Edholm can you give #5 a whirl and see if this does it for you?

@dragonsinth I can verify that it works perfectly. I also tried different ports on the GCS emulator for good measure. Thanks for the quick fix! :blush:

**Comment by dragonsinth** [comment]
Awesome!  We'll get this merged shortly.

**Comment by dragonsinth** [comment]
Fixed
