### ISSUE TITLE
Bucket.Delete doesn't return an error

### ISSUE THREAD

**Issue by LeoCBS** [fullstorydev/emulators#7]
Hi, First of all, congratulations on great work on these Google Emulators.

I am trying to use a storage emulator to test one golang application that uses GCS. But when I try test error on delete bucket that doesn't exist bucket. The emulator doesn't return any error to inform that Bucket doesn't exist.

The real GCS API returns one error when I try to delete on the bucket that doesn't exist.

Is this behavior expected by this emulator?

**Comment by franklinlindemberg** [comment]
@LeoCBS I believe I fixed you issue with my last merge. Could you please double check it?

🇧🇷
