### ISSUE TITLE
Pluggable storage layer interface can't be implemented

### ISSUE THREAD

**Issue by iangudger** [fullstorydev/emulators#8]
The storage layer is pluggable, but the [interface](https://github.com/fullstorydev/emulators/blob/2c243ed01e7d3a48c1654bb196d19fa1aa24f01e/storage/gcsemu/store.go#L11) contains private types, so it can't be implemented by any type outside of the `gcsemu` package. Neither of the two included storage implementations meet my needs, so I would like to be able to provide my own.

What do you think about exporting `gcsemu.httpBaseUrl`?

**Comment by dragonsinth** [comment]
Oops! Yes that's a big oversight, and unintended.

Are there any other helper methods, like stuff in `meta.go` that you'd need to implement your storage layer?

**Comment by dragonsinth** [comment]
I gotchu fam 4c5d4f5c29790227c28adb55ee44853597e2e517
